apiVersion: v1
kind: Secret
metadata:
  name: owncloud
  labels:
    app: owncloud
type: Opaque
data:
  # Create these password by running
  # echo -n "your_password_here" | base64
  # and pasting the output in here
  mariadb_root_password: Y2hhbmdlbWVtYXJpYWRi
  owncloud_admin_password: Y2hhbmdlbWVvd25jbG91ZA==
